[project]
name = "pyspark-alura"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "notebook>=7.5.1",
    "pandas[parquet]>=2.3.3",
    "pyspark[sql]>=4.1.0",
    "seaborn>=0.13.2",
]
